# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example
  
  pod 'JonHomeiOSCore', :path => '../'


  target 'exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exampleUITests' do
    # Pods for testing
  end

end
