name: deploy_to_cocoapods

on:
  push:
    tags:
      - 'v_*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export tag=$(git describe HEAD --abbrev=0 --tags `git rev-list --tags --max-count=1`)
        export podspec_version=${tag:2}
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
